[package]
name = "projman"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
iced = { version =  "0.14.0", features = ["svg", "tokio"] }
directories = "6.0.0"
git2 = "0.20.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.11"
tokei = "14.0.0"
