use std::path::PathBuf;

use crate::{error::Error, project::Project, templates::template::Template};

#[derive(Debug, Clone)]
pub enum Message
{
    Tick,
    Opened(usize),
    Selected(usize),
    Deselected,
    Updated,
    Edited(usize),
    EditConfirmed,
    EditCanceled,
    EditProjectNameChanged(String),
    EditProjectRepoChanged(String),
    RepoOpened,
    Removed,
    RemoveConfirmed,
    RemoveCanceled,
    RemoveProjectFolderToggled(bool),
    Created,
    CreateConfirmed,
    ProjectDirCreated(Result<String, Error>),
    ProjectRepoCloned(Result<String, Error>),
    ProjmanFileCreated(Result<String, Error>),
    DirStructureCreated(Result<String, Error>),
    ProjectFilesCreated(Result<String, Error>),
    BuildCommandExecuted(usize, Result<String, Error>),
    CommitedProjmanInit(Result<String, Error>),
    ProjectAddedToJson(Result<Vec<Project>, Error>),
    CreateFinished(Result<(), Error>),
    CreateCanceled,
    NewProjectNameChanged(String),
    NewProjectTemplateChanged(Template),
    NewProjectRepoChanged(String),
    NewProjectPathChanged(PathBuf),
    CreationErrorCopied,
    Imported,
    ImportConfirmed,
    ImportCanceled,
    ImportProjectPathChanged(String),
    NonexistantRestored,
    NonexistantRemoved,
    RemoveNonexistantFinished(Result<usize, Error>),
    NotificationRemoved(usize),
    NotificationCopied(usize),
    SideBarToggled,
}
